### ISSUE TITLE
Collaborate with manifesto project

### ISSUE THREAD

**Issue by Dispader** [unbroken-dome/gradle-gitversion-plugin#1]
Looks like you're trying to get information based on Git commits, and I like the abstraction of your tests, here.  Any chance you'd care to collaborate with https://github.com/Dispader/manifesto ?

**Comment by tkrullmann** [comment]
Hi Jake! This is still very much work in progress, documentation is coming soon :-)

The idea is that, in contrast to other approaches that operate on a fixed set of conventional rules (like "git flow"), this plugin should allow you to specify your own rules using a DSL in the gradle script. E.g. to transform a branch name `release/1.0` into version 1.0.x,

```groovy
gitversion {
  onBranch (~/release\/(\d+)\.(\d+)/) {
    version.major = matches[1]
    version.minor = matches[2]
  }
}
```

I will have a look at your project when I find the time!

**Comment by Dispader** [comment]
Oh!  That's indeed a new approach.  I like it.  Carry on, sir!
